services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - exerc07-rede
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    ports:
      - "3001:3000"
    environment:
      MONGODB_URI: mongodb://db:27017/mydatabase 
    depends_on:
      - mongo
    networks:
      - exerc07-rede

  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - mongo_dados:/data/db
    networks:
      - exerc07-rede
    expose:
      - 27017

networks: 
  exerc07-rede: 

volumes: 
  mongo_dados: {} 