version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: exerc08
      POSTGRES_USER: yuri 
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-dados:/var/lib/postgresql/data 
    ports:
      - "5432:5432" 

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: yuri@brigido.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "8080:80" 
    depends_on:
      - db 

volumes:
  db-dados: 